"""empty message

Revision ID: 2c482788362d
Revises: 0ab570b5a154
Create Date: 2020-07-30 10:03:04.924330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c482788362d'
down_revision = '0ab570b5a154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_info',
    sa.Column('oid', sa.String(length=64), nullable=False),
    sa.Column('rid', sa.String(length=16), nullable=True),
    sa.Column('isbn', sa.String(length=32), nullable=True),
    sa.Column('book_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['book.isbn'], ),
    sa.ForeignKeyConstraint(['rid'], ['reader.id'], ),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_table('lead_info',
    sa.Column('oid', sa.String(length=64), nullable=False),
    sa.Column('rid', sa.String(length=16), nullable=True),
    sa.Column('isbn', sa.String(length=32), nullable=True),
    sa.Column('lend_date', sa.DateTime(), nullable=True),
    sa.Column('back_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['book.isbn'], ),
    sa.ForeignKeyConstraint(['rid'], ['reader.id'], ),
    sa.PrimaryKeyConstraint('oid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_info')
    op.drop_table('book_info')
    # ### end Alembic commands ###
