"""empty message

Revision ID: 77f50ad2b6b2
Revises: a5281128e802
Create Date: 2020-07-28 09:47:50.084876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77f50ad2b6b2'
down_revision = 'a5281128e802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('book',
    sa.Column('isbn', sa.String(length=32), nullable=False),
    sa.Column('b_name', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=32), nullable=True),
    sa.Column('press', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('desc', sa.String(length=1024), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['book_category.category'], ),
    sa.PrimaryKeyConstraint('isbn'),
    sa.UniqueConstraint('b_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    op.drop_table('book_category')
    # ### end Alembic commands ###
