"""empty message

Revision ID: 94464ddeedc5
Revises: 2c482788362d
Create Date: 2020-07-31 17:38:13.930147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94464ddeedc5'
down_revision = '2c482788362d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rid', sa.String(length=16), nullable=True),
    sa.Column('isbn', sa.String(length=32), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['book.isbn'], ),
    sa.ForeignKeyConstraint(['rid'], ['reader.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_comment')
    # ### end Alembic commands ###
